In [2]:
import torch

In [3]:
torch.__version__

'1.13.1'

In [51]:
# Tensor is replacment of numpy , math arthmetic operation can be done using tensors (it is the replacement of numpy to use the power of GPU)
### Power of tensors multi parallel processing

In [5]:
import numpy as np

In [7]:
lst = [3,4,5,6]
arr=np.array(lst)

In [10]:
# Convert Numpy to Pytorch Tensors

In [11]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [12]:
### Indexing similar to numpy
tensors[:2]

tensor([3, 4], dtype=torch.int32)

In [13]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [14]:
### Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3] = 100

In [18]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [20]:
arr

array([  3,   4,   5, 100])

In [22]:
### Prevent this by using torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [23]:
tensor_arr[3]=20
print(tensor_arr)
print(arr)

tensor([ 3,  4,  5, 20], dtype=torch.int32)
[  3   4   5 100]


In [24]:
### Zeros and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [28]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [33]:
### converting to 2D array
a = torch.tensor(np.arange(0,15).reshape(5,3))

In [34]:
a[:,0]

tensor([ 0,  3,  6,  9, 12], dtype=torch.int32)

# Arithmetic Operation

In [36]:
a = torch.tensor([3,4,5],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)

In [39]:
print(a+b)

tensor([ 7.,  9., 11.])


In [38]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [40]:
c=torch.zeros(3)
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [41]:
c

tensor([ 7.,  9., 11.])

In [42]:
###Some more operations
a = torch.tensor([3,4,5],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)
torch.add(a,b).sum()

tensor(27.)

# Dot Product and Mult Operations

In [43]:
x = torch.tensor([3,4,5],dtype=torch.float)
y = torch.tensor([4,5,6],dtype=torch.float)

In [44]:
x.mul(y)

tensor([12., 20., 30.])

In [46]:
### dot product ( multiplication and addition)
x.dot(y) # 3*4 + 4*5 + 6*5

tensor(62.)

# Matric multiplication

In [47]:
x = torch.tensor([[1,4,2],[1,5,5]],dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float)

In [48]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [49]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [53]:
x@y # matrix multiplication between x and y

tensor([[55., 53.],
        [90., 92.]])